import { AppSidebar } from "@/components/sidebar-components/app-sidebar";
import HeaderSidebar from "@/components/sidebar-components/header-sidebar";

import { Toaster } from "sonner";
import { SidebarInset, SidebarProvider } from "@/components/ui/sidebar";

import React from "react";
import { CartProdukProvider } from "@/hooks/use-cart-produk";
import { cookies } from "next/headers";

export const metadata = {
	title: "Dashboard | Shipper",
	description: "Generated by create next app",
	icons: {
		icon: [
			{ rel: "icon", url: "/favicon.ico" },
			{
				rel: "icon",
				url: "/logobrand.png",
				type: "image/png",
				sizes: "192x192",
			},
			{
				rel: "icon",
				url: "/logobrand.png",
				type: "image/png",
				sizes: "512x512",
			},
		],
		apple: [{ url: "/logobrand.png", sizes: "180x180", type: "image/png" }],
	},
};

const DashboardLayout = ({ children }) => {
	const userRole = cookies().get("userRole")?.value;
	return (
		<SidebarProvider>
			<Toaster />
			<AppSidebar userRole={userRole} />
			<SidebarInset>
				<HeaderSidebar />
				<div className="p-4">
					<CartProdukProvider>{children}</CartProdukProvider>
				</div>
			</SidebarInset>
		</SidebarProvider>
	);
};

export default DashboardLayout;
